#!/usr/bin/env node
// Bakes a directory of single-icon SVG files into a TS module of IconDef literals.
// Works for any icon package that ships one <svg>-per-file (lucide-static, tabler-icons,
// feather-icons, heroicons/outline, game-icons.net, ...) — not lucide-specific. Accepts
// either a flat directory of .svg files, or one nested one level deep by author (as
// game-icons.net's own repo is laid out) — files directly in sourceDir get no author.
//
// Usage: node scripts/build-icons.mjs <sourceDir> <setName> <outFile>
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const [sourceDir, setName, outFile] = process.argv.slice(2);
if (!sourceDir || !setName || !outFile) {
  console.error("Usage: node scripts/build-icons.mjs <sourceDir> <setName> <outFile>");
  process.exit(1);
}

const SVG_OPEN_TAG_RE = /<svg\b([^>]*)>/i;
const SVG_TAG_RE = /<svg\b[^>]*>([\s\S]*)<\/svg>/i;
const VIEWBOX_RE = /viewBox="([^"]+)"/i;

function titleCase(slug) {
  return slug
    .replace(/\.svg$/i, "")
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

// Icon sets (lucide included) put fill/stroke/etc. on the root <svg>, relying on
// inheritance — but we discard that root tag and keep only its children. Re-apply
// those presentation attributes to a wrapping <g> so recoloring via currentColor
// still works once the markup is standalone. See src/importIcons.ts for the
// runtime-import equivalent.
function extractPresentationAttrs(openTagAttrs) {
  const get = (name) => openTagAttrs.match(new RegExp(`${name}="([^"]*)"`, "i"))?.[1];
  const fill = get("fill");
  const stroke = get("stroke");
  const strokeWidth = get("stroke-width");
  const strokeLinecap = get("stroke-linecap");
  const strokeLinejoin = get("stroke-linejoin");

  const attrs = [];
  if (fill !== undefined) attrs.push(`fill="${fill}"`);
  else if (stroke === undefined) attrs.push(`fill="currentColor"`); // no fill/stroke at all: assume single-color filled icon
  if (stroke !== undefined) attrs.push(`stroke="${stroke}"`);
  if (strokeWidth !== undefined) attrs.push(`stroke-width="${strokeWidth}"`);
  if (strokeLinecap !== undefined) attrs.push(`stroke-linecap="${strokeLinecap}"`);
  if (strokeLinejoin !== undefined) attrs.push(`stroke-linejoin="${strokeLinejoin}"`);
  return attrs.join(" ");
}

// Discovers .svg files directly in sourceDir (author "") and one level of
// subdirectories (author = the subdirectory name, title-cased).
function collectSvgFiles(dir) {
  const found = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".svg")) {
      found.push({ path: join(dir, entry.name), file: entry.name, author: "" });
    } else if (entry.isDirectory()) {
      for (const inner of readdirSync(join(dir, entry.name))) {
        if (inner.endsWith(".svg")) {
          found.push({ path: join(dir, entry.name, inner), file: inner, author: titleCase(entry.name) });
        }
      }
    }
  }
  return found.sort((a, b) => (a.author + a.file).localeCompare(b.author + b.file));
}

const files = collectSvgFiles(sourceDir);
if (files.length === 0) {
  console.error(`No .svg files found in ${sourceDir}`);
  process.exit(1);
}

const authors = new Set(files.map((f) => f.author));

const icons = files.map(({ path, file, author }) => {
  const raw = readFileSync(path, "utf8");
  const openTagMatch = raw.match(SVG_OPEN_TAG_RE);
  const bodyMatch = raw.match(SVG_TAG_RE);
  const viewBoxMatch = raw.match(VIEWBOX_RE);
  if (!bodyMatch || !openTagMatch) throw new Error(`Could not find <svg>...</svg> body in ${file}`);
  // Author folders collide on filename across authors (e.g. both lorc/ and delapouite/
  // ship a sword.svg) — namespace the id by author when there is one.
  const slug = file.replace(/\.svg$/i, "");
  const id = author ? `${author.toLowerCase().replace(/\s+/g, "-")}/${slug}` : slug;
  const presentation = extractPresentationAttrs(openTagMatch[1]);
  const innerBody = bodyMatch[1].trim();
  return {
    id,
    name: titleCase(file),
    author,
    viewBox: viewBoxMatch ? viewBoxMatch[1] : "0 0 24 24",
    svgInner: presentation ? `<g ${presentation}>${innerBody}</g>` : innerBody,
  };
});

const body = icons
  .map(
    (icon) =>
      `  { id: ${JSON.stringify(icon.id)}, name: ${JSON.stringify(icon.name)}, set: ${JSON.stringify(setName)}, ` +
      `author: ${JSON.stringify(icon.author)}, viewBox: ${JSON.stringify(icon.viewBox)}, ` +
      `svgInner: ${JSON.stringify(icon.svgInner)} }`,
  )
  .join(",\n");

const exportName = `${setName.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_ICONS`;

const output = `// AUTO-GENERATED by scripts/build-icons.mjs from ${sourceDir} — do not edit by hand.
// Regenerate by re-running build-icons.mjs against the source icon directory (see package.json).
import type { IconDef } from "../../types";

export const ${exportName}: IconDef[] = [
${body},
];
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, output);
console.log(`Wrote ${icons.length} icons from "${setName}" (${authors.size} authors) to ${outFile}`);
